(()=>{
 const $=id=>document.getElementById(id);let workbook=null,rows=[],errors=[],version=0,downloadURL=null;
 const node=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
 function invalidate(){if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=null;$('download').removeAttribute('href');$('code').value='';$('copy-status').textContent='';$('final').hidden=true;$('setup').hidden=false;$('step3').classList.remove('active');}
 function selected(){return rows.filter(r=>r.date.slice(0,7)===$('month').value);}
 function table(id,data){$(id).replaceChildren(...data.map(r=>{const tr=document.createElement('tr');[r.date,r.amount.toLocaleString('ko-KR')+'원',r.user,r.merchant].forEach(v=>tr.append(node('td',v)));return tr;}));}
 function render(){invalidate();const data=selected();table('rows',data);$('preview').hidden=!data.length;$('count').textContent=`${data.length}건`;$('prepare').disabled=!data.length||!!errors.length;$('step2').classList.toggle('active',data.length>0);$('status').textContent=errors.length?'읽지 못한 행을 엑셀에서 수정한 뒤 다시 선택해 주세요.':data.length?`${$('month').value} · ${data.length}건을 불러왔습니다. 메모 입력 만들기를 눌러 주세요.`:'엑셀 파일을 선택해 주세요.';$('errors').hidden=!errors.length;$('errors').replaceChildren(...errors.map(e=>node('li',e)));}
 function sheet(){rows=[];errors=[];try{const result=CardExcel.readRows(workbook.getWorksheet(Number($('sheet').value)),workbook.properties.date1904);rows=result.rows;errors=result.errors;}catch(e){errors=[e.message];}const months=[...new Set(rows.map(r=>r.date.slice(0,7)))].sort();$('month').replaceChildren(...months.map(m=>{const o=node('option',m);o.value=m;return o;}));$('month').disabled=!months.length;render();}
 $('xlsx').onchange=async e=>{const current=++version;rows=[];errors=[];workbook=null;$('sheet').replaceChildren();$('month').replaceChildren();$('sheet').disabled=$('month').disabled=true;render();const file=e.target.files[0];if(!file)return;$('status').textContent='엑셀을 읽고 있습니다…';try{const w=new ExcelJS.Workbook();await w.xlsx.load(await file.arrayBuffer());if(current!==version)return;const sheets=w.worksheets.filter(CardExcel.mapping);if(!sheets.length)throw Error('날짜·금액·이름·거래처 열을 찾지 못했습니다.');workbook=w;$('sheet').replaceChildren(...sheets.map(s=>{const o=node('option',s.name);o.value=s.id;return o;}));$('sheet').disabled=false;sheet();}catch(e){if(current===version){errors=[e.message];render();}}};
 $('sheet').onchange=sheet;$('month').onchange=render;$('company-url').oninput=invalidate;
 $('back').onclick=()=>{invalidate();$('xlsx').focus();};
 $('copy').onclick=copy;
 async function copy(){const field=document.getElementById('code');try{await navigator.clipboard.writeText(field.value);document.getElementById('copy-status').textContent='복사했습니다. 새 북마크의 URL에 붙여넣으세요.';}catch{field.closest('details').open=true;field.focus();field.select();document.getElementById('copy-status').textContent='주소를 선택했습니다. Ctrl+C로 복사하세요.';}}
 $('prepare').onclick=()=>{try{
  const data=selected();if(!data.length||errors.length)return;let target=null,href='https://gw.estgames.com/apps/billing/cards';
  if($('company-url').value.trim()){const u=new URL($('company-url').value.trim());if(u.origin!=='https://gw.estgames.com'||u.pathname!=='/apps/billing/cards'||!/^\d+$/.test(u.searchParams.get('cardId')||'')||!/^\d+$/.test(u.searchParams.get('periodId')||''))throw Error('회사 카드 상세 페이지 주소를 확인해 주세요.');target={cardId:u.searchParams.get('cardId'),periodId:u.searchParams.get('periodId')};href=u.href;}
  const keys=data.map(r=>JSON.stringify([r.date,r.amount,r.merchant.replace(/\s/g,'').toLowerCase()]));if(new Set(keys).size!==keys.length)throw Error('날짜·금액·거래처가 같은 중복 내역이 있습니다. 엑셀에서 확인해 주세요.');
  invalidate();const month=$('month').value;$('code').value=CorporateMemo.bookmark(data,month,target);$('result-title').textContent=`${month.replace('-','년 ')}월 회사 메모에 사용자 이름 입력`;$('result-info').textContent=`엑셀에서 읽은 ${data.length}건 · ${data.reduce((sum,r)=>sum+r.amount,0).toLocaleString('ko-KR')}원. 아래 이름을 회사 메모에 입력합니다.`;$('company-link').href=href;table('result-rows',data);$('setup').hidden=true;$('final').hidden=false;$('step3').classList.add('active');
  const doc=document.implementation.createHTMLDocument($('result-title').textContent);doc.documentElement.lang='ko';const charset=doc.createElement('meta');charset.setAttribute('charset','utf-8');doc.head.prepend(charset);const viewport=doc.createElement('meta');viewport.name='viewport';viewport.content='width=device-width, initial-scale=1';doc.head.append(viewport);const style=doc.createElement('style');style.textContent=Array.from(document.styleSheets).flatMap(s=>Array.from(s.cssRules||[],r=>r.cssText)).join('\n');doc.head.append(style);const main=doc.createElement('main'),result=$('final').cloneNode(true);result.querySelector('#back').remove();result.querySelector('#download').remove();result.querySelector('#code').textContent=$('code').value;main.append(result);doc.body.append(main);const script=doc.createElement('script');script.textContent=`document.getElementById('copy').onclick=${copy.toString()};`;doc.body.append(script);downloadURL=URL.createObjectURL(new Blob(['<!doctype html>'+doc.documentElement.outerHTML],{type:'text/html;charset=utf-8'}));$('download').href=downloadURL;$('download').download=`${month.replace('-','_')}_회사메모_입력.html`;window.scrollTo({top:0,behavior:'smooth'});
 }catch(e){$('status').textContent=e.message;}};
})();
