const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({headless:true});
 try {
  const page = await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true});
  const errors=[], external=[];
  page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')console.log(m.text())});
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:8765'))external.push(r.url())});
  await page.goto('http://127.0.0.1:8765/receipt-index.html');
  await page.waitForFunction(()=>window.CardMonthly);
  await page.locator('#export').click();
  assert.match(await page.locator('#export-help').innerText(), /영수증 폴더/);
  await page.evaluate(()=>document.fonts.load('16px \"Card Korean\"'));
  assert.equal(await page.evaluate(()=>document.fonts.check('16px \"Card Korean\"')),true);
  const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=900;c.height=600;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,900,600);x.fillStyle='black';x.font='48px Arial';x.fillText('RECEIPT',80,90);x.fillText('2026-08-30',80,180);x.fillText('TOTAL 13,500',80,290);return c.toDataURL('image/png').split(',')[1]});
  const filename='2026_0830(일)_주말 식대_테스트사용자.png';
  await page.locator('#receipt-files').setInputFiles({name:filename,mimeType:'image/png',buffer:Buffer.from(image,'base64')});
  await page.waitForFunction(()=>document.querySelector('#count').textContent==='1');
  await page.locator('#company').setInputFiles(path.join(__dirname,'../작성_결재 _ 법인카드 - ESTgames Groupware.html'));
  await page.waitForFunction(()=>document.querySelector('#company-info').textContent.includes('20건'));
  assert.equal(await page.locator('#rows input[type=number]').count(),0);
  assert.match(await page.locator('#rows').innerText(),/13,500원/);
  assert.equal(await page.locator('#rows select').inputValue(),'0');
  assert.equal(await page.locator('#ready').textContent(),'0');
  await page.locator('#export').click();
  assert.match(await page.locator('#export-help').innerText(), /원본 대조 후 확인/);
  assert.equal(await page.locator('#rows input[type=text]').count(),0);
  assert.equal(await page.locator('.filename-user').innerText(),'테스트사용자');
  assert.equal(await page.locator('#rows select').inputValue(),'0');
  await page.locator('#rows input[type=checkbox]').last().check();
  assert.equal(await page.locator('#ready').textContent(),'1');
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export').click()]);
  const file=await download.path();const output=fs.readFileSync(file,'utf8');
  assert.match(output,/테스트사용자/);assert.match(output,/휴근식대/);
  assert.equal(await page.locator('#download-result a').count(),1);
  const [retry]=await Promise.all([page.waitForEvent('download'),page.locator('#download-result a').click()]);
  assert.equal(retry.suggestedFilename(),download.suggestedFilename());
  await page.screenshot({path:'/tmp/cs-card-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/cs-card-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  // Two identical files are detected by content, even with different names.
  await page.locator('#receipt-files').setInputFiles([{name:filename,mimeType:'image/png',buffer:Buffer.from(image,'base64')},{name:'2026_0830(일)_주말 식대_다른이름.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')}]);
  await page.waitForFunction(()=>document.querySelector('#count').textContent==='2');
  assert.equal(await page.locator('.state').filter({hasText:'동일 파일 중복'}).count(),2);
  assert.equal(await page.locator('#download-result a').count(),0);
  await page.locator('#export').click();
  assert.match(await page.locator('#export-help').innerText(),/동일 파일 중복/);
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  console.log('PASS: company amount display without amount inputs, date recommendations, review gating, export, duplicates, responsive layout; no external requests');
 } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1});
